backend:
  name: git-gateway
  branch: main # Убедись, что ветка называется так же, как в твоём репозитории

media_folder: "images/uploads" # Место для хранения картинок
public_folder: "/images/uploads"

collections:
  - name: "watched" # Раздел для просмотренных фильмов
    label: "Просмотренные фильмы"
    folder: "_data/watched"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Название фильма", name: "title", widget: "string" }
      - { label: "Дата просмотра", name: "date", widget: "date" }
      - { label: "Ник заказчика", name: "viewer", widget: "string" }
      - { label: "Постер", name: "poster", widget: "image" }