backend:
  name: github
  repo: fearow1337f-svg/stream-calculator
  branch: main
  base_url: https://api.decapcms.org
  auth_endpoint: /auth

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "watched"
    label: "Просмотренные фильмы"
    folder: "_data/watched"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Название фильма", name: "searchTitle", widget: "string", hint: "Введи название фильма" }
      - { label: "Постер (ссылка)", name: "poster", widget: "string", required: false, hint: "Можешь вставить ссылку на постер (необязательно)" }
      - { label: "Дата просмотра", name: "date", widget: "date" }
      - { label: "Ник заказчика", name: "viewer", widget: "string" }
      - { label: "ID Кинопоиска", name: "kinopoiskId", widget: "string", required: false }
