backend:
  name: github
  repo: fearow1337f-svg/stream-calculator
  branch: main
  base_url: https://decap-cms-oauth.vercel.app
  auth_endpoint: /auth

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "watched"
    label: "Просмотренные фильмы"
    folder: "_data/watched"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Название фильма для поиска", name: "searchTitle", widget: "string", hint: "Введи точное название, как на Кинопоиске" }
      - { label: "Дата просмотра", name: "date", widget: "date" }
      - { label: "Ник заказчика", name: "viewer", widget: "string" }
      - { label: "Постер", name: "poster", widget: "image", required: false }
      - { label: "ID Кинопоиска", name: "kinopoiskId", widget: "string", required: false }
